config/urls.py
from django.contrib import admin
from django.urls import path, include
from movie import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # /movie/ 링크가 오면 movie의 urls로
    path('movie/',include('movie.urls')),

    path('common/', include('common.urls')),

    path('', views.index, name='index'),  # '/' 에 해당되는 path

    path('rest/', include('movie_api.urls')),
]

movie/urls.py
from django.urls import path

from . import views

#다른 프로젝트와 꼬이지 않게 이름지정
app_name='movie'

urlpatterns = [
    # /movie 요청이 들어오면, view.py 의 index 메서드 연결
    path('', views.index,name='index'),
    
    # /movie/숫자/ 링크를 입력하면, view.py 의 detail 메서드 연결
    path('<int:question_id>/', views.detail ,name='detail'),
    
    # /movie/숫자/vote/ 링크를 입력하면, view.py 의 vote 메서드 연결
    path('<int:question_id>/vote/', views.vote, name='vote'), 
    
    # /movie/숫자/result/ 링크를 입력하면, view.py 의 result 메서드 연결
    path('<int:question_id>/result/', views.result, name='result'),

    # /movie/answer/create/숫자/ 링크를 입력하면, view.py 의 answer_create 메서드 연결
    # 이건 보통 링크를 입력해 접속하지 않고 투표하면 자동으로 이동한다. 
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
]

movie/models.py
# 데이터베이스(sqlite3)에서 models 테이블 가져옴
from django.db import models
# 회원 데이터 가져옴
from django.contrib.auth.models import User

from django.utils import timezone
import datetime

# 관리자 가져옴
from django.contrib import admin

# 경기
class Question(models.Model):
    # 경기제목
    # verbose_name='경기'는 대한 인간이 이해하기 쉬운 이름을 지정하는 데 사용되는 속성
    # 관리자 화면에서 열이름으로 쓰임
    subject = models.CharField(max_length=200, verbose_name='경기')
    # 경기내용
    content = models.TextField()
    # 경기날짜(실제 데이터로 대체예정)
    game_date = models.DateTimeField(verbose_name='경기시간')

    # 관리자 화면에서 was_published_recently 열이름을 '오늘경기'로 대체
    @admin.display(boolean=True, description='오늘경기')
    # 하루내에 게시됐는지를 표시
    def was_published_recently(self):
        return self.game_date >= timezone.now() - datetime.timedelta(days=1)
    # 경기 내용과 날짜를 표시
    def __str__(self):
        return f'경기 : {self.subject}, 날짜: {self.game_date}'

# 선택
class Choice(models.Model):
    # 선택을 경기와 묶어줌, 경기가 삭제되면 선택도 삭제되게 설정
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    # 선택팀 텍스트(토트넘 등등)
    choice_text = models.CharField(max_length=200)
    # 투표수
    votes = models.IntegerField(default=0)

    # [토트넘vs 맨유] 토트넘
    def __str__(self):
        return f'[{self.question.subject}] {self.choice_text}'

# 댓글
class Answer(models.Model):
    # 질문에 해당하는 댓글들을 연결, 질문 지우면 댓글들도 지워짐
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    # 댓글 내용 작성 부분
    content = models.TextField()
    # 댓글 작성 날짜
    answer_date = models.DateTimeField(auto_now_add=True)
    # 작성자 속성,기존에 저장된 값들은 null 처리
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

# 유저의 모델 
class Userinfo(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE, null=True, blank=True)

movie/forms.py
# 폼은 쉽게 말해 페이지 요청시 전달되는 파라미터들을 쉽게 관리하기 위해
# 사용하는 클래스이다. 폼은 필수 파라미터의 값이 누락되지 않았는지, 
# 파라미터의 형식은 적절한지 등을 검증할 목적으로 사용

from django import forms
from movie.models import  Answer

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

movie/views.py
# pyexpat 패키지의 messages 모듈을 가져옵니다.
from pyexpat.errors import messages
# Django의 shortcuts 모듈에서 필요한 기능을 가져옵니다.
from django.shortcuts import get_object_or_404, redirect,render
# Django의 timezone 모듈을 가져옵니다.
from django.utils import timezone
# 현재 앱(.으로 표시)의 models.py에서 모든 모델을 가져옵니다.
from .models import *
#페이징으로 페이지에 보이는 경기 갯수를 제한
from django.core.paginator import Paginator
# Django의 HTTP 응답 클래스들을 가져옵니다.
from django.http import HttpResponseRedirect
# Django의 reverse 함수를 가져옵니다.
from django.urls import reverse
# 데이터베이스의 models에서 F 객체를 가져옵니다.
# 데이터베이스에서 직접 필드 값을 가져와서 계산
from django.db.models import F

from django.http import HttpResponseNotAllowed
# 현재 앱의 forms.py에서 AnswerForm 클래스를 가져옵니다.
from .forms import AnswerForm
# Django의 login_required 데코레이터를 가져옵니다.
from django.contrib.auth.decorators import login_required

# 메인 경기페이지
def index(request):
    # 페이지
    # GET 요청의 매개변수 중 'page'라는 이름의 값을 가져옵니다. 
    # 만약 'page' 매개변수가 요청에 없다면 기본값으로 '1'을 사용
    page = request.GET.get('page', '1')
    # 데이터베이스에서 질문 목록 가져오기, 작성일시 역순으로 정렬
    question_list = Question.objects.order_by('-game_date')
    # 페이지당 10개씩 보여주기
    paginator = Paginator(question_list, 10)
    # 현재 페이지의 Question 객체들을 page_obj 변수에 저장
    page_obj = paginator.get_page(page)
    # 현재 페이지에 해당하는 Question 객체들을 'question_list'라는 변수로 
    # 템플릿에 전달
    context = {'question_list': page_obj}
    return render(request, 'movie/question_list.html', context)

# 상세 경기페이지
def detail(request, question_id):
    # primary key 각 객체를 유일하게 식별하는 주요 식별자입니다. 
    # Question 모델은 일반적으로 각 질문마다 고유한 pk를 가지고 있습니다. 
    # 사용자가 특정 질문에 접근(get)하려고 할 때, 해당 질문의 pk 값을 URL에서 
    # 가져오게 됩니다.
    question = get_object_or_404(Question, pk=question_id)
    current_time = timezone.now()
    context = {'question': question,'current_time': current_time}
    return render(request, 'movie/question_detail.html', context)

# 댓글 작성할때 로그인 필요
@login_required(login_url='common:login')
# 댓글 작성 (redirect해서 detail로 다시 이동)
# question_id는 URL 매핑에 의해 그 값이 전달된다. create/2/ 라는 페이지를
# 요청하면 매개변수 question_id에는 2라는 값이 전달된다.
def answer_create(request, question_id):
    # 우선 어떤 질문에 달린 댓글인지 알아야함
    question = get_object_or_404(Question, pk=question_id)
    # 댓글 등록(post)시
    if request.method == "POST":
        # POST 메서드로 전송된 데이터를 이용하여 AnswerForm 인스턴스를 생성
        form = AnswerForm(request.POST)
        if form.is_valid():
            # 임시 저장하여 answer 객체를 리턴받는다.
            answer = form.save(commit=False)
            # 작성자(author) 속성에 로그인 계정 저장
            answer.author = request.user
            # 실제 저장을 위해 작성일시를 설정한다.
            answer.answer_date = timezone.now()
            # 해당 질문도 저장
            answer.question = question
            answer.save()
            # 데이터베이스 저장후 다시 상세 페이지로 돌아감
            return redirect('movie:detail', question_id=question.id)
    #  답변 등록은 POST 방식만 사용되기 때문에 다른방식(GET)은 안됨
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'movie/question_detail.html', context)

# 투표(완료시 결과페이지(result)로 이동)
@login_required(login_url='common:login')
def vote(request, question_id):
    # 우선 어떤 질문에 달린 투표인지 알아야함
    question = get_object_or_404(Question, pk=question_id)
    
    # 데이터베이스에서 사용자가 해당 질문에 이미 투표했는지 확인
    # 유저가 해당질문에 이미 투표했으면, 이미 투표했다는 문구 출력
    if Userinfo.objects.filter(user=request.user, question=question).exists():
        return render(request, 'movie/question_detail.html', {'question': question, 'error_message': "이미 투표한 사용자입니다."})

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    #선택 안한경우 처리
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'movie/question_detail.html', {'question': question, 'error_message': f"선택이 없습니다. id={request.POST['choice']}"})
    else:
        # F는 데이터베이스에서 현재 값을 가져와 필드 값을 업데이트하므로 다른 사용자가
        # 변경한 값을 덮어씌우지 않는다.
        selected_choice.votes = F('votes') + 1
        # 현재 로그인한 사용자를 저장
        selected_choice.user = request.user  
        selected_choice.save()
        
        # 사용자의 투표 여부 및 투표 항목 업데이트
        user_vote = Userinfo(user=request.user, question=question, choice=selected_choice)
        user_vote.save()
        # 투표 완료하면 결과페이지로 보냄. args는 "arguments"의 줄임말로, 뷰 함수나 
        # URL 패턴에 전달해야 하는 값들을 순서대로 나열하는데 사용냄
        return HttpResponseRedirect(reverse('movie:result', args=(question.id,)))

# 투표 결과페이지
def result(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'movie/result.html', {'question': question})

templates/movie/question_detail.html
<!-- 경기 상세페이지 입니다. -->

<!-- 기본 html 형식과 연결-->
{% extends 'base.html' %}
{% block content %}

<!-- 댓글창 스타일 정의 -->
<style>
    .ntextarea {
        width: 700px; /* 원하는 가로 크기 지정 */
        overflow: auto; /* 스크롤 바가 필요한 경우 나타나도록 설정 */
    }
</style>

<div class="container my-3">
    <!-- 경기제목 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <!-- 카드 레이아웃 my-3는 상하여백 -->
    <div class="card my-3">
        <div class="card-body">
            <!-- 카드 내용 넣는곳 "white-space: pre-line;" 스타일은 텍스트 
                줄바꿈을 유지하도록 합니다.-->
            <div class="card-text ntextarea" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <!-- "badge" 클래스를 사용하여 부가 정보를 표시합니다. 
                "bg-light" 클래스는 배경색을 밝게 지정하고, "text-dark" 
                클래스는 텍스트 색상을 어두운 색상으로 지정 -->
                <div class="badge bg-light text-dark p-2">
                    {{ question.game_date }}
                </div>
            </div>
        </div>
    </div>
    <!-- 투표기간(경기날짜 전) 이라면 -->
    {% if question.game_date > current_time %}
    <!-- views 에 vote 연결 -->
    <form action="{% url 'movie:vote' question.id %}" method="post">
        {% csrf_token %}
        <br>
        {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <!-- 승리예측을 선택하는 라디오 버튼 추가 -->
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <!-- 버튼에 대한 설명(예>토트넘, 리버풀) -->
            <label for="choice{{ forloop.counter }}">
                {{ choice.choice_text }}
            </label>
            <!--띄워쓰기 두번 -->
            &nbsp&nbsp
        {% endfor %}
    <!-- 승리 예측 선택후 제출(vote) 버튼 추가 -->
    <input type="submit" value="Vote" class="">
    </form>
    <!-- 이미 투표에 참여했다면 -->
    {% elif error_message %}
        <p>{{ error_message }}</p>

    {% else %}
        <p>투표 기간이 아닙니다.</p>
    {% endif %}

    <br><br>
    <!-- 현재 댓글창 출력 -->
    <h9 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 댓글이 있습니다.</h9>
    <br>
    {% for answer in question.answer_set.all %}
        [{{ answer.answer_date }}]&nbsp&nbsp&nbsp {{ answer.author.username }} : {{ answer.content }}
    <br>
    {% endfor %}
    <!-- 댓글 등록 -->
    <form action="{% url 'movie:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}

        <!-- 오류표시 Start -->
        {% include "form_errors.html" %}

        <!-- 하위 요소들을 수평으로 배치하기 위한 Flexbox 레이아웃 -->
        <div class="d-flex">
            <!-- textarea는 우선 로그인 상태에서만 접근가능하고,텍스트 입력란
            ntextarea 클래스는 사용자 정의 CSS 스타일을 적용
            rows 속성은 입력란의 초기 행 수를 1로 설정
            onkeypress 이벤트 핸들러를 등록, 이벤트 타겟은 아래에 정의됨 -->
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
            name="content" id="content" class="form-control" rows="1" onkeypress="submitOnEnter(event)"></textarea>
            <!-- btn btn-primary 클래스는 부트스트랩에서 제공하는 버튼 스타일 -->
            <input type="submit" value="등록" class="btn btn-primary" rows="5">
        </div>
    </form>
    
    <!-- 엔터를 눌러도 댓글이 등록되게 자바스크립트 코드 추가-->
    <script>
        function submitOnEnter(event) {
            // 쉬프트와 함께누르면 일반 줄바꿈으로 인식
            if (event.key === 'Enter' && !event.shiftKey) {
                // 아무것도 입력하지 않고 등록하려고하면 막음
                if (event.target.value.trim() === ''){
                    alert('텍스트를 입력하세요.')}
                // 입력된 텍스트가 비어있지 않은 경우
                else{
                    // 이벤트(enter)의 기본 동작(submit)을 방지합니다. 
                    event.preventDefault();
                    // 사용자가 직접 제출 버튼을 누르지 않고 JavaScript 코드를
                    // 사용하여 폼을 서버에 제출
                    event.target.form.submit();
                }
            }
        }
    </script>
</div>
{% endblock %}

templates/movie/question_list.html
<!-- 경기 일정이 나오는 메인화면입니다. -->

<!-- 기본 html 형식과 연결-->
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <!-- <thead>는 HTML 테이블의 헤더(제목) 부분을 정의 -->
        <thead>
        <!-- <tr> 테이블 내부에서 행을 정의 -->
        <tr class="table-dark">
            <!-- <th> 요소는 테이블의 헤더 셀의 요소 -->
            <th>번호</th>
            <th>경기</th>
            <th>시작시간</th>
        </tr>
        </thead>

        <tbody>
        <!-- 만약 경기가 있다면  -->
        {% if question_list %}
        <!-- 경기들을 모두 표시 -->
        {% for question in question_list %}
        <tr>
            <!-- <td> 요소는 테이블의 데이터 셀 -->
            <td>{{ forloop.counter }}</td>
            <td>
                <!-- 경기를 누르면 상세페이지 들어갈수 있다. 상세페이지는
                question.id 값들로 링크가 설정돼 있다. -->
                <a href="{% url 'movie:detail' question.id %}">{{ question.subject }}</a>
                <!-- 댓글 개수 표시 -->
                {% if question.answer_set.count > 0 %}
                    <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ question.game_date }}</td>
        </tr>
        {% endfor %}
        
        <!-- 경기가 없다면 -->
        {% else %}
        <tr>
            <td colspan="3">경기가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        <!-- 만약 이전페이지가 있다면 연결해줌 -->
        {% if question_list.has_previous %}
            <!-- <li> 요소를 사용하면 각 항목이 별도의 줄에서 시작되며,
            시각적으로 목록의 구분을 제공. page-item는 각 페이지 번호나 "이전"
            또는 "다음" 버튼을 감싸는 부모요소-->
            <li class="page-item">
                <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <!-- 이전 버튼의 링크를 비활성화로 만듦 -->
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
        {% endif %}

        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}

        <!-- question_list.number에 값을 가져와서 |add:-5 5만큼 빼라
        반대로 |add:5는 5만큼 더하라는 의미이다. 페이지리스트가 현재 페이지 
        기준으로 좌우 5개씩 보이도록 만든다. -->
            {% if page_number >= question_list.number|add:-5|add:-5 and page_number <= question_list.number|add:5 %}
                <!-- 현재 내가 해당 페이지 번호에 있는경우, 그 번호 활성화표시 -->
                {% if page_number == question_list.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                <!-- 아닌경우 그냥 일반페이지 표시 -->
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                {% endif %}
            {% endif %}
        {% endfor %}
        
        <!-- 다음페이지 -->
        <!-- 다음페이지 있을경우 -->
        {% if question_list.has_next %}
            <li class="page-item">
                <!-- 다음페이지 링크 생성 -->
                <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
            </li>
        <!-- 다음페이지 없다면 -->
        {% else %}
            <!-- 다음페이지 링크 비활성화 -->
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
{% endblock %}

templates/movie/result.html
<!-- 투표 제출후 나오는 결과 페이지 입니다. -->
{% extends 'base.html' %}
{% block content %}

<h1>{{ question.subject }}</h1>
<br><br>
<h5>현재 투표수</h5><br>
<!-- 질문의 답변들, 각답변의 투표갯수를 출력 -->
{% for choice in question.choice_set.all %}
    <label>
        {{ choice.choice_text }} : {{ choice.votes }}
    </label>
    <br>
    투표한 사용자들:
        {% for user_vote in choice.userinfo_set.all %}
            {{ user_vote.user.username }},
        {% endfor %}
    <br><br>
{% endfor %}
{% endblock %}