common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    # 로그인,LoginView 클래스를 사용하여 사용자 인증을 처리합니다.
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    
    # 로그아웃
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    # 회원가입요청시 views의 signup 실행
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from movie import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # /movie/ 링크가 오면 movie의 urls로
    path('movie/',include('movie.urls')),

    path('common/', include('common.urls')),

    path('', views.index, name='index'),  # '/' 에 해당되는 path

    path('rest/', include('movie_api.urls')),
]

movie/urls.py
from django.urls import path

from . import views

#다른 프로젝트와 꼬이지 않게 이름지정
app_name='movie'

urlpatterns = [
    # /movie 요청이 들어오면, view.py 의 index 메서드 연결
    path('', views.index,name='index'),
    
    # /movie/숫자/ 링크를 입력하면, view.py 의 detail 메서드 연결
    path('<int:question_id>/', views.detail ,name='detail'),
    
    # /movie/숫자/vote/ 링크를 입력하면, view.py 의 vote 메서드 연결
    path('<int:question_id>/vote/', views.vote, name='vote'), 
    
    # /movie/숫자/result/ 링크를 입력하면, view.py 의 result 메서드 연결
    path('<int:question_id>/result/', views.result, name='result'),

    # /movie/answer/create/숫자/ 링크를 입력하면, view.py 의 answer_create 메서드 연결
    # 이건 보통 링크를 입력해 접속하지 않고 투표하면 자동으로 이동한다. 
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
]

templates/base.html
<!-- 표준 html 형식으로 맞춤 -->
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- HTML 문서의 문자 인코딩을 정의합니다. utf-8은 문자 집합(Encoding)으로서, 
        대부분의 텍스트와 문자를 처리하는 데 사용되는 광범위한 유니코드 문자 세트 -->
    <meta charset="utf-8">
    <!-- 뷰포트는 사용자가 웹 페이지를 보는 디바이스 화면의 영역을 나타냅니다. 
    width=device-width는 뷰포트의 너비를 디바이스의 화면 너비에 맞추라는 의미 
    initial-scale=1 웹 페이지가 초기 로딩 시 100% 배율로 표시되도록 설정
    shrink-to-fit=no 뷰포트가 작을 때 텍스트가 자동으로 축소되지 않도록 설정-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- 부트 스트랩 CSS 연결 -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <title>Hello!</title>
</head>
<body>
<!-- 네비게이션바 html 연결 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
{% endblock %}

<!--메뉴버튼 사용위해 Bootstrap JS 연결 -->
<script src="{% static 'bootstrap.min.js' %}"></script>

</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
    <div class="alert alert-danger">
        <!-- 필드 에러 -->
        {% for field in form %}
            <!-- 폼에 오류가 있는지 확인 -->
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}

        {% endfor %}
        <!-- 넌필드 오류 -->
        {% for error in form.non_field_errors %}
        <div>
            <strong>{{ error }}</strong>
        </div>
        {% endfor %}
    </div>
{% endif %}

<!-- 
필드 오류: 사용자가 폼에 입력한 데이터가 필드에 대한 기대와 맞지 않을 때
넌-필드 오류 : 여러 필드 간의 관계나 폼 전체에 영향을 주는 오류입니다. 
예를 들어, 비밀번호와 비밀번호 확인 필드가 일치하지 않는 경우 -->

templates/navbar.html
<!-- 네비게이션 바 입니다. -->

<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'movie:index' %}"><h1>승부의 신</h1></a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <!-- 사용자가 인증돼있으면(로그인) 로그아웃 나오게 -->
                    {% if user.is_authenticated %}
                        <!-- 누르면 로그인->로그아웃 상태됨 -->
                        <a class="nav-link" href="{% url 'common:logout' %}">
                        {{ user.username }} (로그아웃)</a>
                    <!-- 반대 상태면 로그인 나오게 -->
                    {% else %}
                    <!-- 누르면 로그아웃->로그인 바뀜 -->
                        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                        <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>